model_config:
  vocab_size: 32768
  hidden_size: 256
  intermediate_size: 512
  num_hidden_layers: 8
  hidden_dropout: 0.0
  hidden_act: "silu"
  max_position_embeddings: 2048
  rope_theta: 10000.0
  use_cache: True
  tie_word_embeddings: True
  num_attention_heads: 2
  num_key_value_heads: 1

training_args:
  seed: 233
  dataset_path: "/workspace/Doge/datasets/pretrain_dataset"
  logging_steps: 100
  max_train_steps: 8000
  per_device_train_batch_size: 1
  do_eval: True
  eval_steps: 100
  per_device_eval_batch_size: 1
  optim: "adamw_torch_fused"
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1.0e-8
  learning_rate: 0.008
  warmup_ratio: 0.02
  cooldown_ratio: 0.2
  weight_decay: 0.01
  save_safetensors: True
  save_steps: 1000
  bf16: True
  max_grad_norm: 1.0
  gradient_accumulation_steps: 256
