model_config:
  vocab_size: 32768
  hidden_size: 512
  intermediate_size: 1024
  num_hidden_layers: 16
  hidden_dropout: 0.0
  hidden_act: "silu"
  max_position_embeddings: 2048
  rope_theta: 10000.0
  use_cache: True
  tie_word_embeddings: True
  num_attention_heads: 4
  num_key_value_heads: 4
  is_moe: True
  num_cdmmoe_experts: 1024
  num_cdmmoe_heads: 2
  num_cdmmoe_experts_per_head: 4
  private_expert_retrieval_size: 256

training_args:
  seed: 233
  dataset_path: "/workspace/Doge/datasets/pretrain_dataset"
  logging_steps: 100
  max_train_steps: 40000
  per_device_train_batch_size: 1
  do_eval: True
  eval_steps: 100
  per_device_eval_batch_size: 1
  learning_rate: 0.0006
  warmup_ratio: 0.1
  min_lr_rate: 0.1
  weight_decay: 0.01
  save_safetensors: True
  save_steps: 1000
  bf16: True
  max_grad_norm: 1.0
  gradient_accumulation_steps: 256
