finetuning_args:
  seed: 233
  dataset_path: "/workspace/Doge/datasets/finetune_dataset"
  logging_steps: 100
  num_train_epochs: 2
  per_device_train_batch_size: 1
  do_eval: True
  eval_steps: 100
  per_device_eval_batch_size: 1
  learning_rate: 0.0008
  warmup_ratio: 0.1
  min_lr_rate: 0.1
  weight_decay: 0.01
  save_safetensors: True
  save_steps: 1000
  bf16: True
  max_grad_norm: 1.0
  gradient_accumulation_steps: 128
  dataset_num_proc: 8
  max_seq_length: 8192
  packing: True
