finetuning_args:
  seed: 233
  dataset_path: "./datasets/smoltalk_processed"
  logging_steps: 100
  num_train_epochs: 1
  per_epoch_max_steps: 1
  per_device_train_batch_size: 1
  do_eval: False
  eval_steps: 100
  per_device_eval_batch_size: 1
  learning_rate: 0.00006
  warmup_ratio: 0.1
  min_lr_rate: 0.1
  weight_decay: 0.01
  save_safetensors: True
  save_steps: 100
  bf16: True
  max_grad_norm: 1.0
  gradient_accumulation_steps: 16
  dataset_num_proc: 8
  max_seq_length: 2048
  packing: True
