model:
  vocab_size: 32768
  hidden_size: 768
  num_hidden_layers: 16
  hidden_bias: False
  hidden_dropout: 0.0
  hidden_act: "silu"
  max_position_embeddings: 16384
  rope_theta: 10000.0
  use_cache: True
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2
  num_attention_heads: 6
  num_inner_values: 6
  cross_domain_intermediate_size: 3072
  private_expert_intermediate_size: 768
  num_cdmmoe_experts: 768
  num_cdmmoe_heads: 2
  num_cdmmoe_experts_per_head: 4
