model:
  vocab_size: 32768
  hidden_size: 1024
  num_hidden_layers: 24
  hidden_bias: False
  hidden_dropout: 0.0
  hidden_act: "silu"
  max_position_embeddings: 16384
  rope_theta: 10000.0
  use_cache: True
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2
  num_attention_heads: 8
  num_inner_values: 8
  cross_domain_intermediate_size: 4096
  private_expert_intermediate_size: 1024
  num_cdmmoe_experts: 1024
  num_cdmmoe_heads: 2
  num_cdmmoe_experts_per_head: 4
