model:
  vocab_size: 32768
  hidden_size: 2048
  intermediate_size: 8192
  num_hidden_layers: 32
  hidden_bias: False
  hidden_dropout: 0.0
  hidden_act: "silu"
  max_position_embeddings: 16384
  rope_theta: 10000.0
  use_cache: True
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2
  num_attention_heads: 16
  num_inner_values: 16
  inner_values_retrieval_size: 128
  private_expert_retrieval_size: 256
  num_cdmmoe_experts: 8192
  num_cdmmoe_heads: 8
  num_cdmmoe_experts_per_head: 16

train:
  dataset_path: "/workspace/Doge/datasets/pretrain_datasets"
  logging_steps: 100
  num_train_epochs: 1
  per_epoch_max_steps: 160000
  eval_steps: 100
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  learning_rate: 0.0002
  warmup_ratio: 0.1
  min_lr_rate: 0.1
  save_safetensors: True
  save_steps: 100
  bf16: True
  max_grad_norm: 1.0
  gradient_accumulation_steps: 4096