model:
  vocab_size: 32768
  hidden_size: 256
  num_hidden_layers: 8
  hidden_bias: False
  hidden_dropout: 0.0
  hidden_act: "silu"
  max_position_embeddings: 16384
  rope_theta: 10000.0
  use_cache: True
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2
  num_attention_heads: 4
  num_inner_values: 2
  cross_domain_intermediate_size: 1024
  private_expert_intermediate_size: 256
  num_cdmmoe_experts: 256
  num_cdmmoe_heads: 2
  num_cdmmoe_experts_per_head: 4

train:
  logging_steps: 100
  do_train: True
  max_steps: 2000
  do_eval: True
  eval_strategy: "steps"
  eval_steps: 100
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  learning_rate: 0.0008
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine_with_min_lr"
  min_lr_rate: 0.1
  save_safetensors: True
  save_strategy: "steps"
  save_steps: 100
  bf16: False
  max_grad_norm: 1.0
  gradient_accumulation_steps: 256